### ISSUE TITLE
Ability to show/hide Info icon

### ISSUE THREAD

**Issue by lantoli** [concordion/concordion-logging-tooltip-extension#2]
Hi,
would it possible to add the ability to show/hide the Info icons ?

It could be a link / button / etc, maybe used with an extension attribute.

Could be display "hidden" (so no visual elements are moved), or "none" but in that case elements would move (but in the other hand sentences wouldn't have "holes" for non-visible icons).

It'd be also interested that when be set in one page and then you navigate to other pages it is kept, for example if icons are hidden and you navigate to other page (generated with run commands) icons keep hidden.

Thanks.

**Comment by Tip-Sy** [comment]
Hi there,

Your project looked interesting so I forked concordion-logging-tooltip-extension and I implemented a solution for this feature :)

Basically I added the possibility to show/hide the tooltip (hence the info icon) with any Button. You just need to use the Custom Configuration to do so (see below):

```Java
        String loggers = "carbon.CarbonCalculatorTest, selenium.events";
        @Extension
        public ConcordionExtension extension =
            new LoggingTooltipExtension(loggers, Level.FINE, false);
        
        // New code:
        Button myButton = new Button("Show/hide tooltip");
        extension.setToggleTooltipButton(myButton);
```

I will soon add a test case for my code, and send a pull request when I'm done. I am also thinking of updating your demo project as well, to illustrate how this feature works.

Please let me know if you have any suggestion in the meantime.

Cheers

**Comment by nigelcharman** [comment]
Great, thanks. 

I'd have never thought to use the java.awt classes. Looking at the [java.awt.Button constructor](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/awt/Button.java#Button.%3Cinit%3E%28java.lang.String%29), it throws an exception if used in a headless environment, so I'm somewhat wary of it. Maybe create our own Button interface if you want to abstract it?

Are there some accompanying JavaScript and CSS changes? 

Have you got this working? It would be great if you updated the demo project too.

**Comment by Tip-Sy** [comment]
Thanks, your opinion is interesting. I thought of creating our own interface too, but I was affraid it might be like reinventing the wheel. I'm glad we both agree on this, and it is definitely safer because of this exception. I will modify my code to create a new interface.

I've commited the back-end but nothing for the front-end yet. I am currently working on the Demo project and added some JS code into the HTML page. As for the CSS, I will add some style to get the button "less ugly" than the default one! ;)

I will soon test it inside the demo project, and also commit some JUnit tests. I want to be sure it is completely working before sending any pull request. I'll let you know when I'm done.

(By the way, I work on this only once a week as I'm quite busy these days, that's why it takes so long for me to respond. Sorry about that!)

**Comment by Tip-Sy** [comment]
I've finished the development of the feature, I tested it and it works fine! :)

Eventually I've added a JS file to also show/hide tooltips with an HTML button.

I've also updated the Demo project, and sent a pull request on both of the repos. It would be great if you could also update the *github.io* output of the Demo.

See my pull request:
- on [concordion-logging-tooltip-extension](https://github.com/concordion/concordion-logging-tooltip-extension/pull/3)
- on [concordion-logging-tooltip-extension-demo](https://github.com/concordion/concordion-logging-tooltip-extension-demo/pull/2)

Let me know if everything's okay for you, or if you need anything else.

**Comment by fankee** [comment]
Why is this still showing as open? Is there some further development required here? 
If yes, I would like to contribute. Else, please close it , so it's not misleading.

**Comment by Tip-Sy** [comment]
This issue is still open because my PR hasn't been accepted yet. I don't think further development is required but it was a long time ago, so I might be wrong. Have a nice day!
